//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donate
    {
        public int IdOfDonate { get; set; }
        public Nullable<int> Sponsor { get; set; }
        public Nullable<int> Runner { get; set; }
        public string Donate_Company { get; set; }
        public Nullable<int> Donate_RUB { get; set; }
    
        public virtual runner runner1 { get; set; }
        public virtual sponsor sponsor1 { get; set; }
    }
}
