//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathone
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class marathoneEntities : DbContext
    {
        private static marathoneEntities _context;
        public marathoneEntities()
            : base("name=marathoneEntities")
        {
        }

        public static marathoneEntities GetContext()
        {
            if (_context == null)
                _context = new marathoneEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Donate> Donates { get; set; }
        public virtual DbSet<runner> runners { get; set; }
        public virtual DbSet<Sex> Sexes { get; set; }
        public virtual DbSet<sponsor> sponsors { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
