//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathone
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int IdOfStaff { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string vacancy { get; set; }
    }
}
